namespace Dotnetools.WabiSabi.Crypto.CredentialRequesting;

public record ZeroCredentialsRequestData(ZeroCredentialsRequest CredentialsRequest, CredentialsResponseValidation CredentialsResponseValidation);
